name: 'Manage DNS Record'
description: 'Validate, create, update, or delete a DNS record using the Cloudflare API'
inputs:
  auth-token:
    description: 'Cloudflare API token'
    required: true
  zone-id:
    description: 'DNS zone ID'
    required: true
  record-type:
    description: 'Type of the DNS record'
    required: true
  record-name:
    description: 'Name of the DNS record'
    required: true
  record-content:
    description: 'Content of the DNS record'
    required: true
  action:
    description: 'Action to perform on the DNS record'
    required: true
  ttl:
    description: 'Time to live for DNS record'
    required: false
    default: '1'
  comment:
    description: 'Comment for DNS record'
    required: false
  proxied:
    description: 'If true, DNS record will be proxied through Cloudflare'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - run: chmod +x ${{ github.action_path }}/main.sh
      shell: bash
    - run: ${{ github.action_path }}/main.sh "${{ inputs.auth-token }}" "${{ inputs.zone-id }}" "${{ inputs.record-type }}" "${{ inputs.record-name }}" "${{ inputs.record-content }}" "${{ inputs.action }}" "${{ inputs.ttl }}" "${{ inputs.comment }}" "${{ inputs.proxied }}"
      shell: bash
